\documentclass{article}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{hyperref}
\usepackage{url}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage[backend=bibtex]{biblatex}
\usepackage[margin=2.5cm]{geometry}
\usepackage{caption}
\usepackage{subcaption}


\def\referencepath{../../References/references.bib}
\def\sectiontitle#1{\subsection*{\cite{#1}\citetitle{#1}\citeyear{#1}}}
\def\dc#1{$#1\,^{\circ}\mathrm{C}$}
\def\mycite#1{\citeauthor{#1} (\citeyear{#1})}

\addbibresource{\referencepath}

\def\referencepath{../../References/references.bib}
\def\sectiontitle#1{\subsection*{\cite{#1}\citetitle{#1}\citeyear{#1}}}
\def\dc#1{$#1\,^{\circ}\mathrm{C}$}
\def\mycite#1{\citeauthor{#1} (\citeyear{#1})\textsuperscript{\cite{#1}}}

\addbibresource{\referencepath}


\title{Knitr Template}
\author{Zachary Foster}
\date{\today}

<<setup, include=FALSE>>=
#R library imports
library(knitr)
library(xtable)
# set global chunk options
opts_chunk$set(fig.align='center', 
               fig.show='asis', 
               fig.lp="", 
               error=FALSE, 
               cach=FALSE, 
               dpi=600, 
               include=FALSE, 
               echo=FALSE, 
               tidy=TRUE, 
               out.width=".9\\linewidth", 
               fig.width = 8, 
               external=FALSE, 
               results='markup',
               message=FALSE)
#read_chunk('insert file name here for code externalization ')
@

\begin{document}
\maketitle

\begin{minipage}[b]{0.55\linewidth}

I decided to explore the structure of 354aa protein of unknown function from \textit{Pelagibacter} strain 7214 using a variety of structural prediction methods.
I submitted the unknown sequence to the Phyre2 server using the normal mode. 
62 residues (18\% of the total sequence) hit a heptosyltransferase with 85.4\% confidence (Figure \ref{fig:phyre2}).
The two next best hits were to a glycosyl transferase and a glycosidase.
I also submitted the sequence to SWISS-MODEL using the \texttt{Build Model} function. 
The top hit was to a light-independent protochlorophyllide reductase subunit B, but was not estimated to be significant (Figure \ref{fig:swiss}). 
Next, the query was submitted to iTASSER.
The best hits were to PDB proteins with a hydroxycinnamoyltransferase function.
All 10 top hits were some kind of transferase. 
The best hit had 98\% coverage, but only 8\% sequence identity (Figure \ref{fig:itasser}).
Function Prediction using COFACTOR and binding site prediction suggested similarity to acetyltransferases.


I then searched ProSite for hits to the query using the \texttt{ScanProsite} tool, but none were found.
PFAM was also searched and only one hit to a protein of unknown function was returned (Figure \ref{fig:pfam}).
I attempted to used SSCP (Secondary Structural Content Prediction), but I was unable to access the webpage; all links to it did not work. 
I searched PDB using the query sequence and no matches were returned.
Finally I submitted the PDB file returned by Phyre2 to the Dali server. 
The top matches were of 13\% identity to a lipopolysaccharide heptosyltransferase-1 and the structure seemed to overlap well for a portion of the target (Figure \ref{fig:dali})

Overall, the results weakly suggest that the protein is some kind of transferase, but there is little confidence in the prediction. 
Most of the programs used aligned only 20-40\% of the query sequences and had very low sequence identity.
There were multiple iTASSER alignments of nearly full length and of acceptable quality, typically to various types of transerases.
\end{minipage}%
\hfill
\begin{minipage}[b]{0.38\linewidth}
  \centering
  
  \includegraphics[width=\linewidth]{itasser.png}
  \captionof{figure}{Top iTASSER result 3D alignment}
  \label{fig:itasser}
  
  \includegraphics[width=\linewidth]{dali.png}
  \captionof{figure}{Dali Server result}
  \label{fig:dali}

\end{minipage}%

\includegraphics[width=\linewidth]{phyre2.png}
\captionof{figure}{Phyre2 results}
\label{fig:phyre2}


\includegraphics[width=\linewidth]{swiss.png}
\captionof{figure}{SWISS-MODEL results}
\label{fig:swiss}

\includegraphics[width=\linewidth]{pfam.png}
\captionof{figure}{PFAM result}
\label{fig:pfam}


\printbibliography
\end{document}