\documentclass{article}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{hyperref}
\usepackage{url}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage[backend=bibtex]{biblatex}
\usepackage[margin=2cm]{geometry}
\usepackage{caption}
\usepackage{subcaption}


\def\referencepath{../../../References/references.bib}
\def\sectiontitle#1{\subsection*{\cite{#1}\citetitle{#1}\citeyear{#1}}}
\def\dc#1{$#1\,^{\circ}\mathrm{C}$}
\def\mycite#1{\citeauthor{#1} (\citeyear{#1})}

\addbibresource{\referencepath}

\title{Lab Report 1}
\author{Zachary Foster}
\date{\today}

<<setup, include=FALSE>>=
#R library imports
library(knitr)
library(xtable)
# set global chunk options
opts_chunk$set(fig.align='center', 
               fig.show='asis', 
               fig.lp="", 
               error=FALSE, 
               cach=FALSE, 
               dpi=600, 
               include=FALSE, 
               echo=FALSE, 
               tidy=TRUE, 
               out.width=".9\\linewidth", 
               fig.width = 8, 
               external=FALSE, 
               results='markup',
               message=FALSE)
#read_chunk('insert file name here for code externalization ')
@

\begin{document}

\maketitle










\begin{figure}[ht]
\centering
\begin{minipage}{.45\textwidth}
  \centering
  \includegraphics[width=.7\linewidth]{dotplot}
  \captionof{figure}{Dot plot of contigs vs. the sequence they were derived from. }
  \label{fig:dotplot}
\end{minipage}%
\hspace{10pt}%
\begin{minipage}{.45\textwidth}
  \centering
  \includegraphics[width=.7\linewidth]{coverage_hist}
  \captionof{figure}{Distribution of contig average coverage.}
  \label{fig:histogram}
\end{minipage}%
\end{figure}

\printbibliography

\end{document}